name: SonarQube Analysis

on:
  push:
    branches:
      - main
      - develop

jobs:
  sonarqube_analysis:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      
      - name: Set up JDK
        uses: actions/setup-java@v2
        with:
          java-version: '11' # or any Java version you prefer

      - name: Build with Gradle
        run: ./gradlew clean build

      - name: SonarQube Scan
        uses: SonarSource/sonarcloud-github-action@v1
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
          SONAR_HOST_URL: ${{ secrets.SONAR_HOST_URL }}
